name: Linting

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  run-linting:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Run install
      - name: Run Install
        run: npm install

      - name: Run Formatting
        run: npm run format

      - name: Run Linting
        run: npm run lint

