name: CoverageReport

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  run-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Run install
      - name: Run Install
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: coverage/coverage-final.json
          name: react-mui-notify

